/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "DATABASE_CONNECTION_STRING": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MessageConsumer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MessageQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TELEGRAM_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Webhook": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}