/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "CHROMIUM_LAYER_ARN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CronErrorNotificationTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "CronSuccessNotificationTopic": {
      "arn": string
      "type": "sst.aws.SnsTopic"
    }
    "DATABASE_CONNECTION_STRING_PERSISTER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_CONNECTION_STRING_TELEGRAM_BOT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MessageConsumer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "MessageQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "PROXY_HOST_PORT": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PROXY_PASS": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PROXY_USER": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TELEGRAM_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Webhook": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}