name: SST Deploy to Production

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write # Required for AWS OIDC
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Clean and install all dependencies
        run: |
          echo "Running fresh CI install for CI/CD environment..."
          npm run ci-install
      
      - name: Generate SST types for tests
        run: |
          echo "Generating SST type definitions..."
          npx sst diff --stage prod
      
      - name: Run tests
        run: npx jest --clearCache && npm test
      
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_PROD_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Verify AWS access
        run: |
          echo "Verifying AWS access..."
          aws sts get-caller-identity
          

      - name: Deploy to production
        id: deploy
        run: |
          echo "Deploying to production stage..."
          echo "Note: Chromium layer should be uploaded manually before this deployment"
          npx sst deploy --stage prod
        env:
          NODE_ENV: production
          
      - name: Log deployment information
        run: |
          echo "🚀 Production deployment completed successfully!"
          echo "Stage: prod"
          echo "Environment: production"
          echo "Region: ${{ env.AWS_REGION }}"
          echo "Commit: ${{ github.sha }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Note: Chromium layer managed manually via upload-layer.sh"
